# Generated by Django 4.1.3 on 2022-11-20 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("salon_api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="duration",
            field=models.DurationField(verbose_name="Duration (hh:mm:ss)"),
        ),
    ]
